# Generated by Django 3.2.12 on 2022-12-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_ime', models.CharField(max_length=100)),
                ('profesor_prezime', models.CharField(max_length=100)),
                ('profesor_placa', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Profesori',
            },
        ),
        migrations.CreateModel(
            name='Ucionica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucionica_broj', models.PositiveIntegerField()),
                ('ucionica_kvadratura', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ucionice',
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('predmet_naziv', models.CharField(max_length=100)),
                ('predmet_opis', models.TextField()),
                ('ucionica', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ucionica')),
                ('predmet_predavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor')),
            ],
            options={
                'verbose_name': 'Predmet',
                'verbose_name_plural': 'Predmeti',
            },
        ),
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucenik_ime', models.CharField(max_length=100)),
                ('ucenik_prezime', models.CharField(max_length=100)),
                ('ucenik_razrednik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor')),
                ('ucenik_predmeti', models.ManyToManyField(to='main.Predmet')),
            ],
            options={
                'verbose_name_plural': 'Ucenici',
            },
        ),
    ]
